---
apiVersion: v1
kind: List
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: spring-boot-admin-k8s-webservice
    labels:
      app: spring-boot-admin
      group: codecentric
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: spring-boot-admin
      group: codecentric
    type: NodePort
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: spring-boot-admin
      group: codecentric
    name: spring-boot-admin
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: spring-boot-admin
        group: codecentric
    template:
      metadata:
        labels:
          app: spring-boot-admin
          group: codecentric
      spec:
        containers:
          - name: spring-boot-admin
            image: marcnuri/demo-spring-boot-admin:manual
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
                name: http
                protocol: TCP
            securityContext:
              privileged: false
